from datetime import datetime
from pathlib import Path
from config import BASE_DIR

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, HRFlowable,
    )
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def generate_pdf_report(case_data: dict, evidence: list, timeline: list,
                        ai_analysis: str = "") -> str:
    if not HAS_REPORTLAB:
        return "ReportLab not installed. Run: pip install reportlab"

    output_dir = BASE_DIR / "data" / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)

    filename = f"investigation_{case_data.get('id', 0)}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = output_dir / filename

    doc = SimpleDocTemplate(str(filepath), pagesize=A4,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"],
                                  fontSize=20, spaceAfter=6)
    heading_style = ParagraphStyle("CustomHeading", parent=styles["Heading1"],
                                    fontSize=14, spaceAfter=8, spaceBefore=12)
    body_style = ParagraphStyle("CustomBody", parent=styles["Normal"],
                                 fontSize=10, spaceAfter=6)

    story.append(Paragraph("Traffic Sentinel - Investigation Report", title_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Case Information", heading_style))
    case_info = [
        ["Case Name", case_data.get("case_name", "N/A")],
        ["Case ID", str(case_data.get("id", "N/A"))],
        ["Status", case_data.get("status", "N/A")],
        ["Created", case_data.get("created_at", "N/A")],
        ["Confidence", f"{case_data.get('confidence', 0):.0%}"],
    ]
    t = Table(case_info, colWidths=[2 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    if case_data.get("conclusion"):
        story.append(Paragraph("Conclusion", heading_style))
        story.append(Paragraph(case_data["conclusion"], body_style))
        story.append(Spacer(1, 12))

    story.append(Paragraph("Evidence", heading_style))
    if evidence:
        evidence_data = [["Type", "Description", "Source", "Reliability"]]
        for ev in evidence:
            evidence_data.append([
                ev.get("evidence_type", "N/A"),
                ev.get("description", "N/A")[:80],
                ev.get("source", "N/A"),
                ev.get("reliability", "N/A"),
            ])
        t = Table(evidence_data, colWidths=[1.2 * inch, 3 * inch, 1.2 * inch, 1 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No evidence recorded.", body_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Timeline", heading_style))
    if timeline:
        for event in timeline:
            ts = event.get("timestamp", "")
            etype = event.get("alert_type", event.get("type", "Event"))
            severity = event.get("severity", "N/A")
            story.append(Paragraph(
                f"<b>{ts}</b> - {etype} [{severity}]",
                body_style,
            ))
    else:
        story.append(Paragraph("No timeline events recorded.", body_style))
    story.append(Spacer(1, 12))

    if ai_analysis:
        story.append(Paragraph("AI Security Analyst Analysis", heading_style))
        for line in ai_analysis.split("\n"):
            if line.strip():
                story.append(Paragraph(line.strip(), body_style))
        story.append(Spacer(1, 12))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Paragraph(
        f"Generated by Traffic Sentinel on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(story)
    return str(filepath)
